name: NetFx

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore recording-addons-watson-csharp.sln

    - name: Set up local configuration
      run: copy "recording-addons-watson-csharp\Local.config.example" "recording-addons-watson-csharp\Local.config"

    - name: Build Web App
      run: msbuild recording-addons-watson-csharp.sln /verbosity:minimal
